### ISSUE TITLE
infinitescroll console error w/ 1.2.4 in Chrome 45 w/ TamperMonkey

### ISSUE THREAD

**Issue by nthdegreeburns** [llamasoft/Puca-Power#13]
Just installed via TamperMonkey in Chrome 45. Throwing an inifinitescroll not a function (???) JS error.

This happens w/ and w/o AdBlock extension turned on. Several other extensions running, including Goo.gl shortener, bit.ly shortener, Buffer and Vimium.

**Comment by nthdegreeburns** [comment]
ERROR: Execution of script 'Puca Power' failed! $(...).infinitescroll is not a function

**Comment by llamasoft** [comment]
Working on a fix.

**Comment by llamasoft** [comment]
Probably fixed in the current release.  Let me know if the problem persists!

**Comment by nthdegreeburns** [comment]
I'll give it a whirl using TamperMonkey...

**Comment by camaroman86v6** [comment]
I'm experiencing an infinite scroll error in Firefox. I have to open the page and scroll down one tick with my mouse wheel in order to load the next set of names. If I leave the page alone and walk away, it only loads up to the Fs, so I miss most of the trades I could have loaded.
