### ISSUE TITLE
Function alert

### ISSUE THREAD

**Issue by SpacemaanSpiff** [llamasoft/Puca-Power#15]
The alert function is not worth using. Wondering if there is any progress on the issue posted on this reddit thread:

https://www.reddit.com/r/magicTCG/comments/34exxt/introducing_puca_power_a_free_utility_for_better/cqu1tuf

Thanks for a great utility, and I will be donating!

**Comment by llamasoft** [comment]
Which aspect?  The on-change alert or the not-enough-points issue?

**Comment by llamasoft** [comment]
Fixed in version 1.4.2, an option has been added to only alert on new trade bundles or old trade bundles with new cards.
