### ISSUE TITLE
Enhancing the adding a card experience

### ISSUE THREAD

**Issue by pedromcunha** [llamasoft/Puca-Power#16]
Currently (correct me if I'm wrong) PucaTrade only allows you to add copies of a card once for both haves and wants unless you import a set of cards. So say you wanted to add 4 copies of a card you would have to search and add the same card four times. I think it would be a nice feature to add a quantity input to this field which defaults to 1 but can be incremented to an X amount.

Wanted to throw this idea out there to see if it is helpful. Implementation would be pretty easy I imagine.

**Comment by llamasoft** [comment]
I feel like this is doable but I also feel like it's out of scope of what Puca Power is meant to do (trade alerts).

Might be a good UserScript candidate if anybody is interested in putting it together.
