### ISSUE TITLE
Large Match Lists

### ISSUE THREAD

**Issue by crashoverride42** [llamasoft/Puca-Power#17]
I have a lot of cards on my haves list. When I go to the Send a card page, I only see letters P-Z if I sort backwards by username. Pucapower will not alert me on any trade from users with usernames A-O unless I sit there on the Send a card page and scroll, forcing it to load more of the alphabet. I'm missing out on getting trade alerts because of it. Is there a way for the script to force re-loading of the rest of the alphabet?

**Comment by llamasoft** [comment]
Fixed in version 1.4.0
