### ISSUE TITLE
Infinite scrolling issue

### ISSUE THREAD

**Issue by getbent4** [llamasoft/Puca-Power#18]
For some reason, whether or not I have infinite scrolling checked or not (Google Chrome), puca-power will only search my first 60 or so trades (unless I physically scroll down to "unveil" other trades.  Is it me, or didn't it always do that itself (I've been using this program for a few months)?

**Comment by camaroman86v6** [comment]
That's the same as the issue I posted more than 2 weeks ago. Still no response.

No idea if there is a piece of code that will autoload the rest of the match list.

**Comment by getbent4** [comment]
thanks.

**Comment by getbent4** [comment]
It is frustrating, as getting trades to show up is now very tedious.

**Comment by llamasoft** [comment]
Fixed in version 1.4.0

**Comment by getbent4** [comment]
Thanks!
