### ISSUE TITLE
PucaPower not working at all now?

### ISSUE THREAD

**Issue by llopis** [llamasoft/Puca-Power#19]
I can't get PucaPower 1.3.0 to work at all anymore. It displays the normal PucaPower UI, but when I press start, it doesn't do anything: it doesn't filter entries or users, and it doesn't detect any trades.

Is there some change in PucaTrade that caused PucaPower to break perhaps? Or is it something on my end?

**Comment by llamasoft** [comment]
Just tried it out.  Works just fine for me.

Check your JavaScript console and let me know if there are any errors present.

**Comment by llopis** [comment]
I think my reply didn't come through, so here it is:

Uncaught TypeError: Cannot read property 'trim' of undefinedpucaPower.parseTradeTable @ pucaPower.js?1456431586303&_=1456431579788:400(anonymous function) @ pucaPower.js?1456431586303&_=1456431579788:1056x.event.dispatch @ jquery.1.10.2.min.js:5v.handle @ jquery.1.10.2.min.js:5x.event.trigger @ jquery.1.10.2.min.js:5k @ jquery.1.10.2.min.js:6r @ jquery.1.10.2.min.js:6

Using latest Chrome on MacOS.

The exception happens here:

cardSet  = $(curFields).eq(0).find('img.iconExpansion').attr('title').trim();

I think I have some weird cards that have no expansion icon (like Vanguard). So maybe just add a check to make sure they're valid?

**Comment by llamasoft** [comment]
Fixed!  Thanks for the stack trace!
