### ISSUE TITLE
Stopped working altogether

### ISSUE THREAD

**Issue by davidilopez** [llamasoft/Puca-Power#2]
Version 1.0a4 doesn't work for me at all. I've tried using my usual settings (Refresh every 10 seconds, alert for bundles over 600, filter cards under 500) and it didn't filter at all. Then I tried it with bundles over 10 points, refresh every 10 seconds, no filtering, and it doesn't alert or refresh.

I'm on Chrome version 42.0.2311.90 m.

**Comment by llamasoft** [comment]
Try clearing your browser's cache and reloading the page with Ctrl+F5.  There's a good chance that the control form and the scripts got out of sync.

Also, what method are you using to load the program?  Copy/paste or bookmarklet?

**Comment by llamasoft** [comment]
I've pushed a new release that should fix the JavaScript/controls from getting out of sync.  If the issue persists on the new version (v1.1), feel free to open a new issue.
