### ISSUE TITLE
Error after clicking confirm on trade popup

### ISSUE THREAD

**Issue by tbrisco** [llamasoft/Puca-Power#20]
I am an avid active user of this utility and I LOVE it!!

A few days ago, I started getting a javacript error. I load my Available Trades page, click my Puca Power link, click Start, and wait for the utility to highlight some trades for me.  I scroll to a highlighted trade, click Send Card, and get the confirm window.  When I click the confirm button in the popup the popup goes away, but the black overlay doesn't.  The trade isn't registered with Puca, either.

If I try sending this without having clicked the Puca Power Start button, I don't have the problem.

The error message is "Uncaught TypeError: Cannot read property 'cardPts' of undefined".  The line number is 1138.  The line itself is below:

cardPts = this.cardData['uc_' + url.split('/').pop()].cardPts || 0;

**Comment by llamasoft** [comment]
The issue should be fixed now.  Thanks for the detailed error report.  It really helps with pinning down the issue.

In the last update I got a bit overzealous with cleaning unused memory structures when reloads complete.  I totally forgot that `cardData` was accessed when a card is sent.  It's no longer automatically purged.
