### ISSUE TITLE
Highlights disappear after trade committed

### ISSUE THREAD

**Issue by teddytug** [llamasoft/Puca-Power#21]
Running Pucapower 1.4.3, using browser shortcut method. Behaviour seems to cross web browsers, but in particular I am using Chrome 45.0.2454.101 m.

When I start puca power, the complete list of available trades is parsed correctly, everything works as expected. However, as soon as I click to Send a Card, the highlighted lines all reset to normal view with no highlights. Seems like the page refresh breaks it.

**Comment by llamasoft** [comment]
The page reload is initiated by PucaTrade itself, not Puca Power, so preventing the refresh without interfering with how PucaTrade works is non-trivial.  I'll play around with hiding the `loadTableData` function to prevent PucaTrade from forcing page reloads but it may end up silently breaking something.

If I get something tested and working, I'll push out an update ASAP.

**Comment by llamasoft** [comment]
This should be fixed in the current release (v1.4.4).
