### ISSUE TITLE
No search results

### ISSUE THREAD

**Issue by szwanger** [llamasoft/Puca-Power#26]
I can't get any results from Puca-Power.  After I click Start under "Auto-Refresh Page", the page just sits there.  See screenshot:
![puca-power screenshot](https://cloud.githubusercontent.com/assets/19912492/16014355/d4a07e4e-315e-11e6-8beb-0428fc1742a0.png)

**Comment by llamasoft** [comment]
I just checked and it worked just fine for me.

In the JavaScript console, please run `pucaPower.debugLevel = 3;`, hit Start, then send me what the console shows.  Please also include your browser name and version.

**Comment by szwanger** [comment]
I'm using Firefox 47.0.

 [3] - Loaded 261 trades pucaPower.js:126:13
      [3] - Loaded 263 trades pucaPower.js:126:13
      [3] - Loaded 316 trades pucaPower.js:126:13

I'm now got results but it's grouping them by card instead of by trader, which isn't very helpful.  Also, if I open up a new tab to search for people who want a specific card, then all the Puca-Power search results disappear.

**Comment by llamasoft** [comment]
Puca Power uses the table sorting method you've selected.  You can click one of the column headings to change the sort.  The sort will take effect on the page refresh.

As for searching clearing the result table, that's a PucaTrade issue and not something I can speak to.
