### ISSUE TITLE
Uncaught DOMException

### ISSUE THREAD

**Issue by MarcosMorelli** [llamasoft/Puca-Power#27]
Maybe Puca changed the Trades html.
Check the log attached.

[pucatrade.com-1466262472829.txt](https://github.com/llamasoft/Puca-Power/files/321793/pucatrade.com-1466262472829.txt)

**Comment by llamasoft** [comment]
Strange, I don't seem to be having any issues.  What OS, browser, and browser version are you using?

**Comment by finchc10** [comment]
I had the same issue...

Windows 10, Google Chrome version 51.0.2704.103 m

But, I also had AdBlock. I turned AdBlock off for the site and it started working again.
