### ISSUE TITLE
Maybe bug?

### ISSUE THREAD

**Issue by ghost** [llamasoft/Puca-Power#28]
Not happening for every card, but it for some cards in Have list, PP1.4.4 believes I've twice the number of cards, triggering false trade alerts. 

Let me know if I can help troubleshoot, what additional info you need, etc?

And as always, thanks for this beauteous script. :)

**Comment by llamasoft** [comment]
It looks like this actually a PucaTrade issue, not a Puca Power one.  (Possible duplicate of #24.)
PucaTrade only checks that you have a card that a user wants, not that you have enough to supply all of their wants.
