### ISSUE TITLE
[Enhancement] Support for different bundle threshold per country

### ISSUE THREAD

**Issue by BartSiwek** [llamasoft/Puca-Power#5]
Typically local postage is cheaper than the postage on the same continent, which in turn is cheaper then the world postage (there are a few cases where it's more complicated too).
In general it would be nice to be able to set the bundle threshold per country so users can adjust what makes sense for them to send.

**Comment by llamasoft** [comment]
Someone else suggested this a while back.  I like the idea, but my main sticking point is coming up with a sane way for the user to input the threshold(s).  Obviously listing out all 67 countries isn't an option.  Even doing it by geographical regions would still be too many options and might not be specific enough.

If you've got any ideas (or better yet, a mock-up) for how the user can specify bundle thresholds it would be very appreciated.

In the meantime, I'll modify the script to parse the country field from the trade table.  It'll make it easier for somebody to fork and modify the script as they please.
