### ISSUE TITLE
Is the minimum Trade Bundle alert actually based on user's available points?

### ISSUE THREAD

**Issue by erickoller** [llamasoft/Puca-Power#6]
With settings of Trade Bundles at 130, Users Pts at 131, this entry kept popping up:
http://imgur.com/IETLKGx
It disappeared if I set the Trade Bundle # to 131.

I don't think it should have been listed because the a minimum trade bundle couldn't be covered by the users points.

**Comment by llamasoft** [comment]
It's a known issue that I currently don't have a workaround for.  Currently, the value of the trade bungle is the sum of the cards or the user's points, whichever is less.  It works a majority of the time, but isn't perfect (hence the warning icons).
If anybody feels like implementing a knapsack problem solver to fix this, I'm more than open to pull requests.
